import type { Piano, Brand, PianoModel, Guide, Testimonial } from '@/types/piano'

// ─── PIANO INVENTORY ──────────────────────────────────────────
export const PIANOS: Piano[] = [
  {
    id: 'p001',
    slug: 'steinway-model-b-2015-satin-ebony',
    title: '2015 Steinway Model B — Satin Ebony',
    brand: 'Steinway & Sons',
    brandSlug: 'steinway',
    model: 'Model B',
    modelSlug: 'model-b',
    year: 2015,
    serialNumber: '608421',
    price: 89500,
    priceDisplay: '$89,500',
    condition: 'Excellent',
    finish: 'Satin Ebony',
    size: '6\'10" (211 cm)',
    isAvailable: true,
    isFeatured: true,
    imageUrls: [
      'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&q=80',
      'https://images.unsplash.com/photo-1552422535-c45813c61732?w=1200&q=80',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=1200&q=80',
    ],
    description: 'A pristine 2015 Steinway Model B in satin ebony — arguably Steinway\'s finest home grand. This instrument has been played by its single owner, a retired concert pianist, in a climate-controlled home environment. The action is crisp, the tone is singing, and the bass is authoritative without overpowering.',
    provenance: 'Single owner. Purchased new from Steinway\'s Boston gallery. Maintained by Steinway-certified technician twice annually since purchase.',
    restorationHistory: 'No restoration needed. Action regulation and voicing performed by Steinway-certified technician in 2024.',
    conditionReport: 'Lid and case: 9.5/10 — hairline scratch near treble leg, otherwise pristine. Keys: 10/10 — original ivory-feel Steinway Keytops, no chips or wear. Action: 10/10 — recently regulated by Steinway technician. Soundboard: 10/10 — no cracks, full crown maintained. Strings: 9/10 — original, no signs of rust. Pedals: 10/10 — all three functioning perfectly.',
    specs: {
      'Length': '6\'10" (211 cm)',
      'Width': '58" (147 cm)',
      'Weight': '683 lbs (310 kg)',
      'Keys': '88',
      'Pedals': '3',
      'Finish': 'Satin Ebony',
      'Serial Number': '608421',
      'Year of Manufacture': '2015',
      'Hammers': 'Original Steinway felt hammers',
      'Strings': 'Original Röslau steel wire',
    },
    tags: ['featured', 'concert-quality', 'single-owner'],
  },
  {
    id: 'p002',
    slug: 'steinway-model-d-1998-concert-ebony',
    title: '1998 Steinway Model D — Concert Grand',
    brand: 'Steinway & Sons',
    brandSlug: 'steinway',
    model: 'Model D',
    modelSlug: 'model-d',
    year: 1998,
    serialNumber: '541223',
    price: null,
    priceDisplay: 'Price on request',
    condition: 'Very Good',
    finish: 'Polished Ebony',
    size: '8\'11¾" (274 cm)',
    isAvailable: true,
    isFeatured: true,
    imageUrls: [
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&q=80',
      'https://images.unsplash.com/photo-1515694346937-94d85e41e93b?w=1200&q=80',
    ],
    description: 'A rare opportunity to acquire a full concert Steinway D — the instrument that graces the stages of Carnegie Hall and Symphony Hall. This 1998 example was retired from a New England conservatory program and fully rebuilt in 2019 by a Steinway-authorized rebuilder.',
    restorationHistory: 'Full rebuild completed 2019: new soundboard (Bolduc), new strings (Röslau), complete action rebuild with new Renner hammers, new bass strings wound by Steinway. Investment: approximately $45,000.',
    conditionReport: 'Post-restoration condition throughout. Case shows minor wear consistent with professional use. All structural components new as of 2019.',
    specs: {
      'Length': '8\'11¾" (274 cm)',
      'Width': '61¾" (157 cm)',
      'Weight': '990 lbs (449 kg)',
      'Keys': '88',
      'Serial Number': '541223',
      'Year of Manufacture': '1998',
      'Rebuilt': '2019',
      'Soundboard': 'Bolduc (2019)',
      'Action': 'Renner (2019)',
    },
    tags: ['concert', 'rebuilt', 'rare'],
  },
  {
    id: 'p003',
    slug: 'bosendorfer-225-2010-vienna',
    title: '2010 Bösendorfer 225 — Polished Ebony',
    brand: 'Bösendorfer',
    brandSlug: 'bosendorfer',
    model: '225',
    year: 2010,
    serialNumber: '48791',
    price: 112000,
    priceDisplay: '$112,000',
    condition: 'Excellent',
    finish: 'Polished Ebony',
    size: '7\'4" (225 cm)',
    isAvailable: true,
    isFeatured: true,
    imageUrls: [
      'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=1200&q=80',
      'https://images.unsplash.com/photo-1552422535-c45813c61732?w=1200&q=80',
    ],
    description: 'The Bösendorfer 225 occupies a singular position in the piano world: Austrian craftsmanship, a sound that prioritizes orchestral warmth over Steinway\'s more focused brilliance. This 2010 example is in exceptional condition and represents outstanding value compared to new pricing.',
    provenance: 'Purchased new from Bösendorfer\'s New York showroom. Single owner, professional musician. Climate-controlled home studio.',
    conditionReport: 'Exceptional throughout. No cracks, no repairs, original hammers with minor reshaping performed in 2022.',
    specs: {
      'Length': '7\'4" (225 cm)',
      'Keys': '88',
      'Weight': '793 lbs (360 kg)',
      'Year': '2010',
      'Origin': 'Vienna, Austria',
    },
    tags: ['austrian', 'warm-tone', 'single-owner'],
  },
  {
    id: 'p004',
    slug: 'steinway-model-m-2008-walnut',
    title: '2008 Steinway Model M — Polished Walnut',
    brand: 'Steinway & Sons',
    brandSlug: 'steinway',
    model: 'Model M',
    modelSlug: 'model-m',
    year: 2008,
    serialNumber: '578445',
    price: 52000,
    priceDisplay: '$52,000',
    condition: 'Very Good',
    finish: 'Polished Walnut',
    size: '5\'7" (170 cm)',
    isAvailable: true,
    isFeatured: false,
    imageUrls: [
      'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=1200&q=80',
      'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&q=80',
    ],
    description: 'The Steinway Model M in polished walnut is a rare find — most home Steinways are ebony. This 2008 example has a warm, resonant character that suits the walnut case perfectly.',
    conditionReport: 'Very good condition throughout. Minor wear to key surfaces. Action slightly heavy — regulation recommended.',
    specs: {
      'Length': '5\'7" (170 cm)',
      'Width': '57" (145 cm)',
      'Weight': '540 lbs (245 kg)',
      'Year': '2008',
      'Finish': 'Polished Walnut',
    },
    tags: ['walnut', 'home-grand'],
  },
  {
    id: 'p005',
    slug: 'bechstein-b-228-2012-ebony',
    title: '2012 Bechstein B 228 — Polished Ebony',
    brand: 'C. Bechstein',
    brandSlug: 'bechstein',
    model: 'B 228',
    year: 2012,
    serialNumber: '193847',
    price: 78000,
    priceDisplay: '$78,000',
    condition: 'Excellent',
    finish: 'Polished Ebony',
    size: '7\'6" (228 cm)',
    isAvailable: true,
    isFeatured: false,
    imageUrls: [
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&q=80',
    ],
    description: 'The Bechstein B 228 is a true professional instrument with a characteristically German sound — clear, balanced, and technically demanding to play. This 2012 example is one of the finest German grands available at this price point.',
    specs: {
      'Length': '7\'6" (228 cm)',
      'Year': '2012',
      'Origin': 'Berlin, Germany',
    },
    tags: ['german', 'professional'],
  },
  {
    id: 'p006',
    slug: 'shigeru-kawai-sk-6-2018',
    title: '2018 Shigeru Kawai SK-6 — Polished Ebony',
    brand: 'Shigeru Kawai',
    brandSlug: 'shigeru-kawai',
    model: 'SK-6',
    year: 2018,
    price: 68000,
    priceDisplay: '$68,000',
    condition: 'Excellent',
    finish: 'Polished Ebony',
    size: '6\'7" (200 cm)',
    isAvailable: true,
    isFeatured: true,
    imageUrls: [
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
    ],
    description: 'Shigeru Kawai represents the pinnacle of Japanese piano craftsmanship. The SK-6 is built with Renner hammers, spruce soundboard, and extraordinary attention to voicing. A world-class instrument at a fraction of the European competition.',
    specs: {
      'Length': '6\'7" (200 cm)',
      'Year': '2018',
      'Hammers': 'Renner',
      'Origin': 'Hamamatsu, Japan',
    },
    tags: ['japanese', 'renner', 'excellent-value'],
  },
  {
    id: 'p007',
    slug: 'steinway-model-s-2001-ebony',
    title: '2001 Steinway Model S — Polished Ebony',
    brand: 'Steinway & Sons',
    brandSlug: 'steinway',
    model: 'Model S',
    modelSlug: 'model-s',
    year: 2001,
    serialNumber: '548762',
    price: 38500,
    priceDisplay: '$38,500',
    condition: 'Good',
    finish: 'Polished Ebony',
    size: '5\'1" (155 cm)',
    isAvailable: true,
    isFeatured: false,
    imageUrls: [
      'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=1200&q=80',
    ],
    description: 'The Model S is Steinway\'s smallest grand — ideal for apartments and smaller rooms where a larger instrument would overpower the space. This 2001 example plays well and represents excellent value.',
    conditionReport: 'Good condition. Some cosmetic wear. Action functions well, voicing could benefit from attention.',
    specs: {
      'Length': '5\'1" (155 cm)',
      'Year': '2001',
    },
    tags: ['compact', 'apartment-grand'],
  },
  {
    id: 'p008',
    slug: 'bluthner-model-6-2005-ebony',
    title: '2005 Blüthner Model 6 — Satin Ebony',
    brand: 'Blüthner',
    brandSlug: 'bluthner',
    model: 'Model 6',
    year: 2005,
    price: 61000,
    priceDisplay: '$61,000',
    condition: 'Very Good',
    finish: 'Satin Ebony',
    size: '6\'3" (190 cm)',
    isAvailable: true,
    isFeatured: false,
    imageUrls: [
      'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=1200&q=80',
    ],
    description: 'Blüthner is Leipzig\'s finest — a piano with a distinctive aliquot stringing system that adds warmth and harmonic richness to the upper register. The Model 6 is a versatile performer in home and professional settings alike.',
    specs: {
      'Length': '6\'3" (190 cm)',
      'Year': '2005',
      'Special Feature': 'Aliquot stringing',
      'Origin': 'Leipzig, Germany',
    },
    tags: ['german', 'aliquot', 'warm-tone'],
  },
]

// ─── BRANDS ───────────────────────────────────────────────────
export const BRANDS: Brand[] = [
  {
    slug: 'steinway',
    name: 'Steinway & Sons',
    country: 'United States / Germany',
    founded: 1853,
    tagline: 'The instrument of the immortals.',
    description: 'Founded in 1853 by Heinrich Engelhard Steinweg in New York City, Steinway & Sons has defined concert piano performance for over 170 years. Nine of ten concert pianists perform on a Steinway. The company\'s Hamburg and New York factories maintain hand-craftsmanship traditions unchanged since the 19th century, with each instrument requiring over a year to produce.',
    whyBuyPreowned: [
      'A pre-owned Steinway retains its value exceptionally well — often appreciating after quality restoration',
      'Hamburg Steinways built before 2000 are widely considered to have superior tonal complexity to newer models',
      'A $45,000 pre-owned Model B outperforms most new $90,000 pianos from other makers',
      'Steinway parts, technicians, and expertise are universally available — service is never a concern',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1600&q=80',
    models: ['Model S', 'Model M', 'Model O', 'Model A', 'Model A3', 'Model B', 'Model C', 'Model D', 'Hamburg S'],
    priceRange: '$30,000 – $200,000+',
    prestige: 'Ultra Premium',
  },
  {
    slug: 'bosendorfer',
    name: 'Bösendorfer',
    country: 'Austria',
    founded: 1828,
    tagline: 'The sound of Vienna.',
    description: 'Founded in Vienna in 1828, Bösendorfer is the world\'s oldest active piano manufacturer. Now owned by Yamaha, Bösendorfer instruments are still built entirely in Vienna with Austrian spruce soundboards and a sound that is uniquely warm, orchestral, and resonant. Famous for models with extended bass range (97 keys on the Imperial).',
    whyBuyPreowned: [
      'Pre-Yamaha acquisition models (pre-2007) are prized by collectors for their pure Viennese character',
      'Bösendorfer\'s tonal character — warm, complex, orchestral — is unmatched by any other maker',
      'Extended bass models offer unique musical possibilities not available on any other instrument',
      'Austrian craftsmanship and premium materials ensure decades of reliable performance',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=1600&q=80',
    models: ['185', '200', '214VC', '225', '280', 'Imperial 97'],
    priceRange: '$60,000 – $300,000+',
    prestige: 'Ultra Premium',
  },
  {
    slug: 'bechstein',
    name: 'C. Bechstein',
    country: 'Germany',
    founded: 1853,
    tagline: 'German precision. Poetic voice.',
    description: 'C. Bechstein, founded in Berlin in 1853 — the same year as Steinway — is the choice of pianists who prefer a more refined, analytically transparent sound. Bechstein instruments are known for their clarity of texture, extraordinary touch sensitivity, and long-term durability. Franz Liszt called the Bechstein "the piano of the future."',
    whyBuyPreowned: [
      'Pre-reunification East German Bechsteins (1950s–1980s) represent exceptional value for the craftsmanship',
      'Bechstein\'s action is widely considered the most responsive of any production piano',
      'German build quality means these instruments play well for 60+ years with proper maintenance',
      'A benchmark for professional pianists who find Steinway\'s sound too bright',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=1600&q=80',
    models: ['A 190', 'B 212', 'B 228', 'C 234', 'D 282'],
    priceRange: '$40,000 – $150,000',
    prestige: 'Ultra Premium',
  },
  {
    slug: 'bluthner',
    name: 'Blüthner',
    country: 'Germany',
    founded: 1853,
    tagline: 'The Leipzig warmth.',
    description: 'Blüthner, founded in Leipzig in 1853, holds a unique place in the piano world through its patented aliquot stringing system — an additional fourth string in the treble register that vibrates sympathetically, adding extraordinary warmth and harmonic richness. Brahms, Tchaikovsky, and Wagner all favored Blüthner instruments.',
    whyBuyPreowned: [
      'Aliquot stringing creates a harmonic richness impossible to find elsewhere',
      'Pre-WWII Leipzig Blüthners are considered among the finest pianos ever built',
      'The warm, singing tone is ideal for Romantic repertoire',
      'Blüthner maintains parts and service worldwide',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1600&q=80',
    models: ['Model 4', 'Model 6', 'Model 10', 'Model 1'],
    priceRange: '$35,000 – $120,000',
    prestige: 'Ultra Premium',
  },
  {
    slug: 'shigeru-kawai',
    name: 'Shigeru Kawai',
    country: 'Japan',
    founded: 1927,
    tagline: 'Master class. Japanese soul.',
    description: 'Shigeru Kawai represents the absolute pinnacle of Kawai\'s artisanal craft — handbuilt in Hamamatsu by master craftsmen with Renner hammers, premium European spruce soundboards, and an extraordinary level of individual attention. These instruments compete directly with Steinway at a significantly more accessible price.',
    whyBuyPreowned: [
      'Pre-owned Shigeru Kawai offers world-class performance at 40-50% of new pricing',
      'Renner hammers and premium European materials throughout',
      'Japanese precision manufacturing ensures remarkable consistency',
      'Outstanding value proposition versus European competition',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e93b?w=1600&q=80',
    models: ['SK-2', 'SK-3', 'SK-5', 'SK-6', 'SK-EX'],
    priceRange: '$30,000 – $120,000',
    prestige: 'Premium',
  },
  {
    slug: 'petrof',
    name: 'Petrof',
    country: 'Czech Republic',
    founded: 1864,
    tagline: 'Bohemian craftsmanship since 1864.',
    description: 'Petrof, founded in Hradec Králové in 1864, is Central Europe\'s finest piano manufacturer and one of the best-kept secrets in the piano world. Built with centuries of Czech craftsmanship tradition, Petrof instruments offer an extraordinarily musical sound at prices that make European luxury accessible.',
    whyBuyPreowned: [
      'Exceptional value — European craftsmanship at Asian prices',
      'Czech spruce soundboards create a warm, singing tone',
      'Strong resale market in Europe and North America',
      'Family-owned since 1864 — quality is personal',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1552422535-c45813c61732?w=1600&q=80',
    models: ['P 173 Breeze', 'P 194 Storm', 'P 210 Wind', 'P 237 Hurricane', 'P 284 Monsoon'],
    priceRange: '$20,000 – $80,000',
    prestige: 'Professional',
  },
  {
    slug: 'kayserburg',
    name: 'Kayserburg',
    country: 'China',
    founded: 2000,
    tagline: 'Pearl River\'s masterwork.',
    description: 'Kayserburg is Pearl River\'s artist-level line, designed in collaboration with German and Austrian engineers and built to world-class standards. The instruments use Renner actions, premium Sitka spruce soundboards, and Röslau strings — the same materials found in Europe\'s finest instruments.',
    whyBuyPreowned: [
      'World-class components at remarkable value pricing',
      'Renner actions and European strings throughout',
      'Growing collector interest as quality recognition increases',
      'Excellent choice for students and professionals on a budget',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=1600&q=80',
    models: ['GH-152A', 'GH-188A', 'KA-212'],
    priceRange: '$15,000 – $50,000',
    prestige: 'Professional',
  },
  {
    slug: 'yamaha',
    name: 'Yamaha',
    country: 'Japan',
    founded: 1887,
    tagline: 'Crafted for performance.',
    description: 'Yamaha\'s CF and CFX concert grands represent the pinnacle of Japanese piano engineering. While mass-market Yamaha models are ubiquitous, the professional CF series instruments — particularly the CF6, CF7, and CFX — are world-class instruments used at the highest levels of performance.',
    whyBuyPreowned: [
      'Professional CF and CFX models are significantly undervalued in the used market',
      'Yamaha\'s reliability is unmatched — these instruments require minimal maintenance',
      'Strong dealer and service network nationwide',
      'CF series instruments offer concert-quality sound at accessible prices',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1600&q=80',
    models: ['CF Junior', 'CF6', 'CF7', 'CFX'],
    priceRange: '$25,000 – $150,000',
    prestige: 'Premium',
  },
  {
    slug: 'wendl-lung',
    name: 'Wendl & Lung',
    country: 'Austria',
    founded: 1854,
    tagline: 'Viennese heritage. Modern soul.',
    description: 'Wendl & Lung, Vienna\'s second historic piano house, produces instruments with a distinctly Viennese tonal character — warm, lyrical, and responsive. A smaller operation than Bösendorfer, Wendl & Lung offers exceptional quality at more accessible prices.',
    whyBuyPreowned: [
      'Authentic Viennese sound at Bösendorfer\'s fraction of the price',
      'Limited production ensures quality attention to each instrument',
      'Austrian materials and craftsmanship throughout',
      'Undervalued in the North American market — an insider\'s choice',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1600&q=80',
    models: ['178', '185', '228'],
    priceRange: '$25,000 – $80,000',
    prestige: 'Premium',
  },
  {
    slug: 'brodmann',
    name: 'Brodmann',
    country: 'Austria / China',
    founded: 2002,
    tagline: 'Viennese design. Global craft.',
    description: 'Brodmann pianos are designed by Austrian master craftsmen and built in China under strict European quality standards. The result is an instrument with genuine musical character — warm, responsive, and musical — at prices that make serious piano ownership accessible to more musicians.',
    whyBuyPreowned: [
      'Professional-quality instrument at consumer pricing',
      'Austrian design heritage in every detail',
      'Excellent entry point into the premium piano market',
      'Strong value retention for the price category',
    ],
    heroImageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1600&q=80',
    models: ['PE 187', 'PE 228'],
    priceRange: '$10,000 – $40,000',
    prestige: 'Professional',
  },
]

// ─── STEINWAY MODELS ──────────────────────────────────────────
export const STEINWAY_MODELS: PianoModel[] = [
  {
    slug: 'model-b',
    brandSlug: 'steinway',
    name: 'Model B',
    type: 'Grand',
    size: '6\'10"',
    sizeInches: '82"',
    weight: '683 lbs (310 kg)',
    stringLength: 'Bass: 77.5" | Treble: 6.4"',
    yearRange: '1884 – present',
    description: 'The Model B is, in our view, the finest home grand Steinway makes. At 6\'10", it produces a full, rich bass, a singing tenor, and a brilliant treble that larger rooms can properly accommodate. It is the instrument of choice for serious home performers and many university practice rooms.',
    highlights: [
      'Ideal balance between home suitability and concert-quality tone',
      'Strong bass without the spatial demands of the Model D',
      'Wide availability in the used market ensures competitive pricing',
      'Retains value exceptionally well — often appreciates with quality restoration',
    ],
    priceGuide: [
      { era: '2010–present', condition: 'Excellent', priceRange: '$75,000 – $95,000' },
      { era: '2010–present', condition: 'Very Good', priceRange: '$60,000 – $75,000' },
      { era: '2000–2009', condition: 'Excellent', priceRange: '$55,000 – $70,000' },
      { era: '2000–2009', condition: 'Very Good', priceRange: '$40,000 – $55,000' },
      { era: '1980–1999', condition: 'Rebuilt/Excellent', priceRange: '$45,000 – $65,000' },
      { era: '1960–1979', condition: 'Rebuilt/Excellent', priceRange: '$35,000 – $55,000' },
    ],
    adjacentModels: [
      { slug: 'model-a', name: 'Model A (6\'2")' },
      { slug: 'model-c', name: 'Model C (7\'5")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&q=80',
  },
  {
    slug: 'model-d',
    brandSlug: 'steinway',
    name: 'Model D',
    type: 'Concert Grand',
    size: '8\'11¾"',
    sizeInches: '107¾"',
    weight: '990 lbs (449 kg)',
    stringLength: 'Bass: 88.5" | Treble: 6.9"',
    yearRange: '1884 – present',
    description: 'The Steinway D is the concert grand — the instrument that graces Carnegie Hall, the Vienna Musikverein, and every major stage in the world. It is rarely appropriate for residential use, but for institutions, performance spaces, and serious collectors, nothing else compares.',
    highlights: [
      'The standard against which all concert grands are measured',
      'Used by 9 of 10 concert pianists worldwide',
      'Maximum tonal range and power of any production piano',
      'Extraordinary investment value — $200,000+ new',
    ],
    priceGuide: [
      { era: '2000–present', condition: 'Excellent', priceRange: '$150,000 – $200,000+' },
      { era: '2000–present', condition: 'Rebuilt', priceRange: '$100,000 – $150,000' },
      { era: '1980–1999', condition: 'Rebuilt/Excellent', priceRange: '$80,000 – $120,000' },
    ],
    adjacentModels: [
      { slug: 'model-c', name: 'Model C (7\'5")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&q=80',
  },
  {
    slug: 'model-m',
    brandSlug: 'steinway',
    name: 'Model M',
    type: 'Grand',
    size: '5\'7"',
    sizeInches: '67"',
    weight: '540 lbs (245 kg)',
    stringLength: 'Bass: 68" | Treble: 5.6"',
    yearRange: '1911 – present',
    description: 'The Model M is Steinway\'s "parlor grand" — the ideal balance between meaningful size and practical footprint for a living room. At 5\'7", it produces enough bass to satisfy serious players while fitting comfortably in most homes.',
    highlights: [
      'The most popular Steinway grand for home use',
      'Wide selection available in the used market',
      'True Steinway sound in a practical package',
      'Ideal for rooms 200–400 sq ft',
    ],
    priceGuide: [
      { era: '2010–present', condition: 'Excellent', priceRange: '$55,000 – $70,000' },
      { era: '2000–2009', condition: 'Excellent', priceRange: '$40,000 – $55,000' },
      { era: '1990–1999', condition: 'Very Good', priceRange: '$28,000 – $40,000' },
      { era: '1970–1989', condition: 'Rebuilt', priceRange: '$30,000 – $45,000' },
    ],
    adjacentModels: [
      { slug: 'model-s', name: 'Model S (5\'1")' },
      { slug: 'model-o', name: 'Model O (5\'10¾")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=1200&q=80',
  },
  {
    slug: 'model-s',
    brandSlug: 'steinway',
    name: 'Model S',
    type: 'Grand',
    size: '5\'1"',
    sizeInches: '61"',
    weight: '484 lbs (220 kg)',
    stringLength: 'Bass: 61.5" | Treble: 5.1"',
    yearRange: '1936 – present',
    description: 'The Model S is Steinway\'s smallest grand — designed for apartments, condominiums, and smaller living spaces where music is still taken seriously. At 5\'1", it is the minimum size at which a Steinway delivers its characteristic sound.',
    highlights: [
      'Perfect for urban apartments and smaller rooms',
      'Genuine Steinway tone in the most compact grand format',
      'Strong demand ensures good resale value',
      'Ideal for rooms 150–250 sq ft',
    ],
    priceGuide: [
      { era: '2010–present', condition: 'Excellent', priceRange: '$40,000 – $55,000' },
      { era: '2000–2009', condition: 'Excellent', priceRange: '$30,000 – $40,000' },
      { era: '1990–1999', condition: 'Very Good', priceRange: '$20,000 – $30,000' },
    ],
    adjacentModels: [
      { slug: 'model-m', name: 'Model M (5\'7")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=1200&q=80',
  },
  {
    slug: 'model-a',
    brandSlug: 'steinway',
    name: 'Model A',
    type: 'Grand',
    size: '6\'2"',
    sizeInches: '74"',
    weight: '638 lbs (290 kg)',
    stringLength: 'Bass: 74" | Treble: 6.1"',
    yearRange: '1878 – present',
    description: 'The Model A sits between the M and the B — at 6\'2", it offers more bass depth than the M while fitting in spaces that cannot accommodate the B. A versatile performer that suits both living rooms and smaller concert venues.',
    highlights: [
      'The "sweet spot" between home and concert',
      'Rich bass that approaches the Model B',
      'Slightly less common than M and B — unique choice',
    ],
    priceGuide: [
      { era: '2010–present', condition: 'Excellent', priceRange: '$65,000 – $80,000' },
      { era: '2000–2009', condition: 'Excellent', priceRange: '$48,000 – $65,000' },
      { era: '1990–1999', condition: 'Very Good', priceRange: '$32,000 – $48,000' },
    ],
    adjacentModels: [
      { slug: 'model-m', name: 'Model M (5\'7")' },
      { slug: 'model-b', name: 'Model B (6\'10")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&q=80',
  },
  {
    slug: 'model-a3',
    brandSlug: 'steinway',
    name: 'Model A3',
    type: 'Grand',
    size: '6\'4"',
    sizeInches: '76"',
    weight: '650 lbs (295 kg)',
    stringLength: 'Bass: 76" | Treble: 6.2"',
    yearRange: '1936 – present',
    description: 'The Model A3 is a refinement of the Model A with a slightly longer scale — 6\'4" versus the A\'s 6\'2". The extended bass strings produce noticeably richer bass response. Often overlooked in favor of the B, the A3 is an excellent value choice.',
    highlights: [
      'Richer bass than the Model A at the same approximate footprint',
      'Often undervalued compared to the B — significant savings opportunity',
      'Suits rooms where a B would be too large',
    ],
    priceGuide: [
      { era: '2000–present', condition: 'Excellent', priceRange: '$55,000 – $72,000' },
      { era: '1990–1999', condition: 'Very Good', priceRange: '$35,000 – $50,000' },
    ],
    adjacentModels: [
      { slug: 'model-a', name: 'Model A (6\'2")' },
      { slug: 'model-b', name: 'Model B (6\'10")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
  },
  {
    slug: 'model-o',
    brandSlug: 'steinway',
    name: 'Model O',
    type: 'Grand',
    size: '5\'10¾"',
    sizeInches: '70¾"',
    weight: '580 lbs (263 kg)',
    stringLength: 'Bass: 71" | Treble: 5.9"',
    yearRange: '1900 – 1983 (discontinued)',
    description: 'The Model O was discontinued in 1983, making all examples at least 40 years old. In its day it was Steinway\'s mid-range offering between the M and the A. Pre-WWII Model O pianos are particularly prized by collectors.',
    highlights: [
      'Discontinued — all examples are vintage (40+ years)',
      'Pre-WWII examples have exceptional tonal depth',
      'Intermediate size between M and A',
      'Collector interest growing',
    ],
    priceGuide: [
      { era: '1960–1983', condition: 'Excellent', priceRange: '$30,000 – $45,000' },
      { era: '1940–1959', condition: 'Rebuilt', priceRange: '$35,000 – $50,000' },
      { era: 'Pre-1940', condition: 'Rebuilt', priceRange: '$40,000 – $60,000' },
    ],
    adjacentModels: [
      { slug: 'model-m', name: 'Model M (5\'7")' },
      { slug: 'model-a', name: 'Model A (6\'2")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e93b?w=1200&q=80',
  },
  {
    slug: 'model-c',
    brandSlug: 'steinway',
    name: 'Model C',
    type: 'Grand',
    size: '7\'5"',
    sizeInches: '89"',
    weight: '756 lbs (343 kg)',
    stringLength: 'Bass: 84" | Treble: 6.6"',
    yearRange: '1879 – present',
    description: 'The Model C is the professional choice — larger than the B but more manageable than the D. At 7\'5", it suits large home music rooms, university recital halls, and professional studios. It delivers nearly concert-grand authority with slightly more practical dimensions.',
    highlights: [
      'Professional-level instrument between the B and D',
      'Ideal for recital halls, recording studios, conservatory rooms',
      'Substantially more affordable than new Model C pricing',
    ],
    priceGuide: [
      { era: '2010–present', condition: 'Excellent', priceRange: '$100,000 – $130,000' },
      { era: '2000–2009', condition: 'Excellent', priceRange: '$80,000 – $100,000' },
      { era: '1990–1999', condition: 'Rebuilt', priceRange: '$65,000 – $85,000' },
    ],
    adjacentModels: [
      { slug: 'model-b', name: 'Model B (6\'10")' },
      { slug: 'model-d', name: 'Model D (8\'11¾")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&q=80',
  },
  {
    slug: 'hamburg-s',
    brandSlug: 'steinway',
    name: 'Hamburg S',
    type: 'Grand',
    size: '5\'1"',
    sizeInches: '61"',
    weight: '484 lbs (220 kg)',
    stringLength: 'Bass: 61.5" | Treble: 5.1"',
    yearRange: '1936 – present',
    description: 'The Hamburg-made Model S is built in Steinway\'s Hamburg factory rather than the New York facility. Hamburg instruments are distinguished by a slightly different action and voicing character — a touch more refined, a touch more European in character.',
    highlights: [
      'Hamburg craftsmanship — prized by European-trained pianists',
      'Subtle tonal differences from New York Steinway S',
      'Rare in the North American market — collector interest',
    ],
    priceGuide: [
      { era: '2010–present', condition: 'Excellent', priceRange: '$45,000 – $60,000' },
      { era: '2000–2009', condition: 'Excellent', priceRange: '$32,000 – $45,000' },
    ],
    adjacentModels: [
      { slug: 'model-s', name: 'New York Model S (5\'1")' },
      { slug: 'model-m', name: 'Model M (5\'7")' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1552422535-c45813c61732?w=1200&q=80',
  },
]

// ─── GUIDES ───────────────────────────────────────────────────
export const GUIDES: Guide[] = [
  {
    slug: 'buying-a-used-steinway',
    title: 'The Complete Guide to Buying a Used Steinway',
    description: 'Everything you need to know before spending $40,000–$120,000 on a pre-owned Steinway — from evaluating condition to negotiating price.',
    readTime: '12 min read',
    category: 'Buying Guide',
    imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&q=80',
    publishedDate: '2026-01-15',
  },
  {
    slug: 'steinway-pricing-guide',
    title: 'Steinway Pricing Guide: What Should You Pay?',
    description: 'Current market prices for every Steinway model by era and condition. Updated quarterly.',
    readTime: '8 min read',
    category: 'Buying Guide',
    imageUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&q=80',
    publishedDate: '2026-02-01',
  },
  {
    slug: 'steinway-vs-bosendorfer',
    title: 'Steinway vs. Bösendorfer: An Honest Comparison',
    description: 'Two legends, two philosophies. A frank comparison of tone, touch, value, and which instrument suits which pianist.',
    readTime: '10 min read',
    category: 'Comparison',
    imageUrl: 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=800&q=80',
    publishedDate: '2026-01-28',
  },
  {
    slug: 'best-steinway-model-for-home',
    title: 'Which Steinway Model is Right for Your Home?',
    description: 'From the compact Model S to the full-size Model B — how to match a Steinway to your room, budget, and musical ambitions.',
    readTime: '9 min read',
    category: 'Buying Guide',
    imageUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&q=80',
    publishedDate: '2026-02-10',
  },
  {
    slug: 'piano-restoration-process',
    title: 'Inside a Piano Restoration: What Actually Happens',
    description: 'A behind-the-scenes look at what a quality piano restoration involves, what it costs, and how to evaluate a restored instrument.',
    readTime: '11 min read',
    category: 'Education',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
    publishedDate: '2026-01-20',
  },
  {
    slug: 'what-to-look-for-used-piano',
    title: 'What to Look for When Buying a Used Piano',
    description: 'The ten things every buyer should inspect — and the three red flags that should stop the sale.',
    readTime: '7 min read',
    category: 'Buying Guide',
    imageUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e93b?w=800&q=80',
    publishedDate: '2026-02-15',
  },
]

// ─── TESTIMONIALS ─────────────────────────────────────────────
export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't001',
    name: 'Dr. Margaret Chen',
    location: 'Boston, MA',
    piano: '2012 Steinway Model B',
    quote: 'Roger spent two hours with me explaining the differences between three Model Bs before I even touched a key. That kind of expertise is what you\'re paying for — not just the piano.',
    rating: 5,
    date: '2025-11-15',
  },
  {
    id: 't002',
    name: 'James Worthington',
    location: 'Providence, RI',
    piano: '2010 Bösendorfer 225',
    quote: 'I\'ve been searching for the right Bösendorfer for three years. Roger found exactly what I was looking for in two weeks. The instrument is extraordinary.',
    rating: 5,
    date: '2025-10-22',
  },
  {
    id: 't003',
    name: 'Sarah Mitchell',
    location: 'Concord, NH',
    piano: '2008 Steinway Model M',
    quote: 'As a piano teacher with a home studio, I needed something my students could aspire to. The Model M Roger sourced for me has transformed my teaching — students actually want to practice.',
    rating: 5,
    date: '2025-12-03',
  },
  {
    id: 't004',
    name: 'Prof. David Nakamura',
    location: 'Cambridge, MA',
    piano: '2018 Shigeru Kawai SK-6',
    quote: 'I was skeptical of the Shigeru Kawai until Roger played it for me. The Renner action is exquisite — comparable to anything I\'ve played at Steinway.',
    rating: 5,
    date: '2025-09-18',
  },
]

// ─── HELPER FUNCTIONS ─────────────────────────────────────────
export function getPianosByBrand(brandSlug: string): Piano[] {
  return PIANOS.filter((p) => p.brandSlug === brandSlug && p.isAvailable)
}

export function getPianosByModel(modelSlug: string): Piano[] {
  return PIANOS.filter((p) => p.modelSlug === modelSlug && p.isAvailable)
}

export function getFeaturedPianos(): Piano[] {
  return PIANOS.filter((p) => p.isFeatured && p.isAvailable)
}

export function getBrand(brandSlug: string): Brand | undefined {
  return BRANDS.find((b) => b.slug === brandSlug)
}

export function getModel(modelSlug: string): PianoModel | undefined {
  return STEINWAY_MODELS.find((m) => m.slug === modelSlug)
}

export function getPiano(slug: string): Piano | undefined {
  return PIANOS.find((p) => p.slug === slug)
}

export function getAvailablePianos(): Piano[] {
  return PIANOS.filter((p) => p.isAvailable)
}
