import type { Payload } from 'payload'

type PianoSeed = {
  title: string
  slug: string
  brandSlug: string
  model: string
  year?: number
  serialNumber?: string
  finish: string
  condition: 'new' | 'used' | 'reconditioned' | 'rebuilt' | 'rebuilt-partial' | 'work-in-progress' | 'display'
  price?: number
  showPrice?: boolean
  retailPrice?: number
  isAvailable: boolean
  isFeatured: boolean
  location?: 'Natick' | 'Burlington' | 'Incoming'
  stockImageUrl?: string
  specifications: {
    length?: string
    width?: string
    stringLength?: string
    keys: number
    pedals?: number
  }
  conditionReport?: string
  tags: Array<{ tag: string }>
}

const PIANO_INVENTORY: PianoSeed[] = [
  {
    title: 'Steinway B',
    slug: 'steinway-model-b-1959-ebony-satin',
    brandSlug: 'steinway',
    model: 'B',
    year: 1959,
    serialNumber: '365132',
    finish: 'Ebony Satin',
    condition: 'rebuilt',
    location: 'Natick',
    price: 79999,
    showPrice: true,
    retailPrice: 150900,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'10.5\"", width: '58"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Blüthner Model 2',
    slug: 'bluthner-model-2-ebony-polish',
    brandSlug: 'bluthner',
    model: '2',
    year: 1999,
    serialNumber: '150457',
    finish: 'Ebony Polish',
    condition: 'used',
    location: 'Burlington',
    price: 74999,
    showPrice: true,
    retailPrice: 226465,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "7'8\"", width: '61"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'European' }],
  },
  {
    title: 'Bösendorfer 214 CS',
    slug: 'bosendorfer-214CS-ebony-satin',
    brandSlug: 'bosendorfer',
    model: '214 CS',
    year: 2000,
    serialNumber: '45572',
    finish: 'Ebony Satin',
    condition: 'reconditioned',
    location: 'Burlington',
    price: 64999,
    showPrice: true,
    retailPrice: 211999,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "7'", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'European' }, { tag: 'Reconditioned' }],
  },
  {
    title: 'Bösendorfer 225',
    slug: 'bosendorfer-225-ebony-polish',
    brandSlug: 'bosendorfer',
    model: '225',
    year: 2015,
    serialNumber: '50141',
    finish: 'Ebony Polish',
    condition: 'used',
    location: 'Natick',
    price: 109999,
    showPrice: true,
    retailPrice: 248999,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "7'4\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'European' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Hamburg Steinway Model A',
    slug: 'hamburg-steinway-a-ebony-polish',
    brandSlug: 'steinway',
    model: 'A',
    year: 1983,
    serialNumber: '484052',
    finish: 'Ebony Polish',
    condition: 'work-in-progress',
    location: 'Burlington',
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'1\"", width: '58"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'European' }, { tag: 'Restored' }],
  },
  {
    title: 'Hamburg Steinway Model S',
    slug: 'hamburg-steinway-s-walnut-satin',
    brandSlug: 'steinway',
    model: 'S',
    year: 1957,
    serialNumber: '357222',
    finish: 'Walnut Satin',
    condition: 'reconditioned',
    location: 'Burlington',
    price: 36999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'1\"", width: '58"', keys: 88, pedals: 2 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'European' }, { tag: 'Restored' }],
  },
  {
    title: 'Schimmel K219',
    slug: 'schimmel-k219-ebony-polish',
    brandSlug: 'schimmel',
    model: 'K219',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Burlington',
    price: 79999,
    showPrice: true,
    retailPrice: 154596,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "7'2\"", width: '60"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'European' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Steinway A',
    slug: 'steinway-model-a-mahogany-satin',
    brandSlug: 'steinway',
    model: 'A',
    year: 1900,
    serialNumber: '97601',
    finish: 'Mahogany Satin',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 39999,
    showPrice: true,
    retailPrice: 210200,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'1\"", width: '58"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway D',
    slug: 'steinway-model-d-1894-ebony-satin',
    brandSlug: 'steinway',
    model: 'D',
    year: 1894,
    serialNumber: '81493',
    finish: 'Ebony Satin',
    condition: 'rebuilt',
    location: 'Natick',
    price: 139999,
    showPrice: true,
    retailPrice: 253900,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "8'11.75\"", width: '60"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway D',
    slug: 'steinway-model-d-1980-ebony-satin',
    brandSlug: 'steinway',
    model: 'D',
    year: 1980,
    serialNumber: '469816',
    finish: 'Ebony Satin',
    condition: 'rebuilt-partial',
    location: 'Burlington',
    price: 99999,
    showPrice: true,
    retailPrice: 253900,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "8'11.75\"", width: '60"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway D',
    slug: 'steinway-model-d-1939-ebony-satin',
    brandSlug: 'steinway',
    model: 'D',
    year: 1939,
    serialNumber: '299829',
    finish: 'Ebony Satin',
    condition: 'work-in-progress',
    location: 'Burlington',
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "8'11.75\"", width: '60"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway B',
    slug: 'steinway-model-b-mahogany-satin',
    brandSlug: 'steinway',
    model: 'B',
    year: 2003,
    serialNumber: '564028',
    finish: 'Mahogany Satin',
    condition: 'used',
    location: 'Natick',
    price: 99999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'10.5\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Rare' }],
  },
  {
    title: 'Steinway A3',
    slug: 'steinway-model-a3-ebony-satin',
    brandSlug: 'steinway',
    model: 'A3',
    year: 1924,
    serialNumber: '228786',
    finish: 'Ebony Satin',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 69999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'4\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway A Louis XV',
    slug: 'steinway-model-a-mahogany-polish',
    brandSlug: 'steinway',
    model: 'A',
    year: 1904,
    serialNumber: '112645',
    finish: 'Mahogany Polish',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 99999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'1\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Rebuilt' }, { tag: 'Rare' }, { tag: 'Designer Case' }],
  },
  {
    title: 'Steinway O',
    slug: 'steinway-model-o-1915-mahogany-satin',
    brandSlug: 'steinway',
    model: 'O',
    year: 1915,
    serialNumber: '173357',
    finish: 'Mahogany Satin',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 69999,
    showPrice: true,
    retailPrice: 157000,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'10.5\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway O',
    slug: 'steinway-model-o-1917-mahogany-satin',
    brandSlug: 'steinway',
    model: 'O',
    year: 1917,
    serialNumber: '189731',
    finish: 'Mahogany Satin',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 69999,
    showPrice: true,
    retailPrice: 157000,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'10.5\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway C',
    slug: 'steinway-model-c-ebony-satin',
    brandSlug: 'steinway',
    model: 'C',
    year: 1883,
    serialNumber: '53403',
    finish: 'Ebony Satin',
    condition: 'rebuilt-partial',
    location: 'Burlington',
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "7'5.5\"", width: '56"', keys: 85, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway M',
    slug: 'steinway-model-m-1926-ebony-satin',
    brandSlug: 'steinway',
    model: 'M',
    year: 1926,
    serialNumber: '248584',
    finish: 'Ebony Satin',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 55999,
    showPrice: true,
    retailPrice: 106200,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'7\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway M',
    slug: 'steinway-model-m-1973-ebony-satin',
    brandSlug: 'steinway',
    model: 'M',
    year: 1973,
    serialNumber: '432996',
    finish: 'Ebony Satin',
    condition: 'reconditioned',
    location: 'Burlington',
    price: 39999,
    showPrice: true,
    retailPrice: 106200,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'7\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Reconditioned' }],
  },
  {
    title: 'Steinway M',
    slug: 'steinway-model-m-mahogany-satin',
    brandSlug: 'steinway',
    model: 'M',
    year: 1920,
    serialNumber: '200437',
    finish: 'Mahogany Satin',
    condition: 'work-in-progress',
    location: 'Burlington',
    price: 59999,
    showPrice: true,
    retailPrice: 143000,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'7\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway S',
    slug: 'steinway-model-s-mahogany-satin',
    brandSlug: 'steinway',
    model: 'S',
    year: 1935,
    serialNumber: '282949',
    finish: 'Mahogany Satin',
    condition: 'work-in-progress',
    location: 'Burlington',
    price: 41999,
    showPrice: true,
    retailPrice: 135700,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'1\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway S',
    slug: 'steinway-model-s-walnut-satin',
    brandSlug: 'steinway',
    model: 'S',
    year: 1993,
    serialNumber: '528306',
    finish: 'Walnut Satin',
    condition: 'reconditioned',
    location: 'Burlington',
    price: 21999,
    showPrice: true,
    retailPrice: 138100,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'1\"", width: '56"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Reconditioned' }],
  },
  {
    title: 'Boston GP163 II',
    slug: 'boston-model-gp163-ebony-satin',
    brandSlug: 'steinway',
    model: 'GP163 II',
    year: 2007,
    serialNumber: 'B160885',
    finish: 'Ebony Satin',
    condition: 'used',
    location: 'Natick',
    price: 15999,
    showPrice: true,
    retailPrice: 35200,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'4\"", width: '58"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }],
  },
  {
    title: 'Petrof 125 M1',
    slug: 'petrof-model-125m1-walnut-polish',
    brandSlug: 'petrof',
    model: '125 M1',
    finish: 'Walnut Polish',
    condition: 'new',
    location: 'Natick',
    price: 31790,
    showPrice: true,
    retailPrice: 31790,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: '49"', width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Upright Piano' }, { tag: 'New' }, { tag: 'European' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Petrof 127 NEXT TC',
    slug: 'petrof-model-127next-white-and-ebony-polish',
    brandSlug: 'petrof',
    model: '127 NEXT TC',
    finish: 'Ebony and White Polish',
    condition: 'new',
    location: 'Natick',
    isAvailable: true,
    isFeatured: false,
    specifications: { length: '50"', width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Upright Piano' }, { tag: 'New' }, { tag: 'European' }, { tag: 'Handcrafted' }, { tag: 'Designer Case' }],
  },
  {
    title: 'Petrof 173 Breeze',
    slug: 'petrof-model-173-ebony-polish',
    brandSlug: 'petrof',
    model: '173 Breeze',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Natick',
    price: 88640,
    showPrice: true,
    retailPrice: 88640,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'4\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'European' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Petrof 194 Storm',
    slug: 'petrof-model-194-ebony-polish',
    brandSlug: 'petrof',
    model: '194 Storm',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Natick',
    price: 98640,
    showPrice: true,
    retailPrice: 98640,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'8\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'European' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Petrof 210 Pasat',
    slug: 'petrof-model-210-ebony-polish',
    brandSlug: 'petrof',
    model: '210 Pasat',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Natick',
    price: 128640,
    showPrice: true,
    retailPrice: 128640,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'10.6\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'European' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Wilhelm Schimmel W123T',
    slug: 'wilhelm-schimmel-w123t-white-polish',
    brandSlug: 'schimmel',
    model: 'W123T',
    finish: 'White Polish',
    condition: 'new',
    location: 'Burlington',
    price: 15999,
    showPrice: true,
    retailPrice: 32258,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: '48.5"', width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Upright Piano' }, { tag: 'New' }, { tag: 'European' }],
  },
  {
    title: 'Bohemia Janecek 185 with Player System',
    slug: 'bohemia-185-mahogany-polish',
    brandSlug: 'bohemia',
    model: '185',
    year: 2009,
    serialNumber: '74241',
    finish: 'Mahogany Polish',
    condition: 'reconditioned',
    location: 'Burlington',
    price: 29999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'1\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Reconditioned' }, { tag: 'Player Piano' }],
  },
  {
    title: 'Bohemia Janecek 185',
    slug: 'bohemia-185-walnut-polish',
    brandSlug: 'bohemia',
    model: '185',
    year: 2000,
    serialNumber: '72906',
    finish: 'Walnut Polish',
    condition: 'reconditioned',
    location: 'Burlington',
    price: 19999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'1\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Reconditioned' }],
  },
  {
    title: 'C. Bechstein Model B',
    slug: 'c-bechstein-b-mahogany-satin',
    brandSlug: 'c. bechstein',
    model: 'B',
    year: 1890,
    serialNumber: '26599',
    finish: 'Mahogany Satin',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 39999,
    showPrice: true,
    retailPrice: 199000,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'11\"", width: '59"', keys: 88, pedals: 2 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'C. Bechstein Model B',
    slug: 'c-bechstein-b-ebony-polish',
    brandSlug: 'c. bechstein',
    model: 'B',
    year: 1900,
    serialNumber: '55402',
    finish: 'Ebony Polish',
    condition: 'rebuilt-partial',
    location: 'Burlington',
    price: 49999,
    showPrice: true,
    retailPrice: 190000,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "6'11\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Schimmel C169TI with Inlay',
    slug: 'schimmel-c169ti-ebony-polish',
    brandSlug: 'schimmel',
    model: 'C169TI',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Burlington',
    price: 69999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'6\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'European' }, { tag: 'Handcrafted' }, { tag: 'Rare' }, { tag: 'Designer Case' }],
  },
  {
    title: 'Schimmel K280',
    slug: 'schimmel-k280-ebony-polish',
    brandSlug: 'schimmel',
    model: 'K280',
    finish: 'Ebony Polish',
    condition: 'display',
    location: 'Burlington',
    price: 99999,
    showPrice: true,
    retailPrice: 254189,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "9'2\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Concert Grand Piano' }, { tag: 'European' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Wilhelm Schimmel W180T',
    slug: 'wilhelm-schimmel-w180t-white-polish',
    brandSlug: 'schimmel',
    model: 'W180T',
    finish: 'White Polish',
    condition: 'new',
    location: 'Burlington',
    price: 31999,
    showPrice: true,
    retailPrice: 69281,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: "5'11\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'European' }],
  },
  {
    title: 'Steinway K52',
    slug: 'steinway-model-k52-mahogany-satin',
    brandSlug: 'steinway',
    model: 'K',
    year: 1994,
    serialNumber: '530977',
    finish: 'Mahogany Satin',
    condition: 'rebuilt',
    location: 'Burlington',
    price: 41999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: '52"', width: '60"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Upright Piano' }, { tag: 'Used' }, { tag: 'Restored' }, { tag: 'Rebuilt' }],
  },
  {
    title: 'Steinway 45',
    slug: 'steinway-model-45-ebony-satin',
    brandSlug: 'steinway',
    model: '45',
    year: 1969,
    serialNumber: '414320',
    finish: 'Ebony Satin',
    condition: 'reconditioned',
    location: 'Burlington',
    price: 9999,
    showPrice: true,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: '45"', width: '60"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Upright Piano' }, { tag: 'Used' }, { tag: 'Reconditioned' }],
  },
  {
    title: 'Schimmel 152',
    slug: 'schimmel-model-152-white-polish',
    brandSlug: 'schimmel',
    model: '152',
    finish: 'White Polish',
    condition: 'used',
    location: 'Incoming',
    isAvailable: false,
    isFeatured: false,
    specifications: { length: "5'", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'Used' }, { tag: 'European' }],
  },
  {
    title: 'Boston UP118S',
    slug: 'boston-model-up118s-oak-satin',
    brandSlug: 'steinway',
    model: 'UP118S',
    year: 1997,
    serialNumber: 'B116557',
    finish: 'Oak Satin',
    condition: 'used',
    location: 'Burlington',
    price: 5999,
    showPrice: true,
    retailPrice: 17800,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: '46.5"', width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Upright Piano' }, { tag: 'Used' }, { tag: 'Reconditioned' }],
  },
  {
    title: 'Essex EUP-123',
    slug: 'essex-model-eup-123',
    brandSlug: 'steinway',
    model: 'EUP-123',
    year: 2014,
    serialNumber: 'E135777C',
    finish: 'Cherry Satin',
    condition: 'used',
    location: 'Natick',
    price: 4299,
    showPrice: true,
    retailPrice: 11700,
    isAvailable: true,
    isFeatured: false,
    specifications: { length: '48"', width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Upright Piano' }, { tag: 'Used' }, { tag: 'Reconditioned' }],
  },

  // ── Shigeru Kawai ──────────────────────────────────────────────────────────
  {
    title: 'Shigeru Kawai SK-2',
    slug: 'shigeru-kawai-sk2-ebony-polish',
    brandSlug: 'shigeru-kawai',
    model: 'SK-2',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Natick',
    price: 79000,
    showPrice: true,
    retailPrice: 79000,
    isAvailable: true,
    isFeatured: false,
    stockImageUrl: 'https://cdn.shopify.com/s/files/1/0740/4670/1723/files/SK-2US_another_angle_50.png?v=1777414635',
    specifications: { length: "5'11\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'Japanese' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Shigeru Kawai SK-3',
    slug: 'shigeru-kawai-sk3-ebony-polish',
    brandSlug: 'shigeru-kawai',
    model: 'SK-3',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Burlington',
    price: 91000,
    showPrice: true,
    retailPrice: 91000,
    isAvailable: true,
    isFeatured: false,
    stockImageUrl: 'https://cdn.shopify.com/s/files/1/0740/4670/1723/files/SK-3L_US_styling.png?v=1777414758',
    specifications: { length: "6'2\"", width: '59"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'Japanese' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Shigeru Kawai SK-5',
    slug: 'shigeru-kawai-sk5-ebony-polish',
    brandSlug: 'shigeru-kawai',
    model: 'SK-5',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Burlington',
    price: 105000,
    showPrice: true,
    retailPrice: 105000,
    isAvailable: true,
    isFeatured: false,
    stockImageUrl: 'https://cdn.shopify.com/s/files/1/0740/4670/1723/files/SK-5L_US_styling.jpg?v=1777416619',
    specifications: { length: "6'7\"", width: '60"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'Japanese' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Shigeru Kawai SK-6',
    slug: 'shigeru-kawai-sk6-ebony-polish',
    brandSlug: 'shigeru-kawai',
    model: 'SK-6',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Natick',
    price: 118000,
    showPrice: true,
    retailPrice: 118000,
    isAvailable: true,
    isFeatured: false,
    stockImageUrl: 'https://cdn.shopify.com/s/files/1/0740/4670/1723/files/SK-6L_US_styling.png?v=1777417103',
    specifications: { length: "7'0\"", width: '61"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'Japanese' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Shigeru Kawai SK-7',
    slug: 'shigeru-kawai-sk7-ebony-polish',
    brandSlug: 'shigeru-kawai',
    model: 'SK-7',
    finish: 'Ebony Polish',
    condition: 'new',
    location: 'Burlington',
    price: 131000,
    showPrice: true,
    retailPrice: 131000,
    isAvailable: true,
    isFeatured: false,
    stockImageUrl: 'https://cdn.shopify.com/s/files/1/0740/4670/1723/files/SK-7L_US_styling.png?v=1777418899',
    specifications: { length: "7'6\"", width: '62"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Grand Piano' }, { tag: 'New' }, { tag: 'Japanese' }, { tag: 'Handcrafted' }],
  },
  {
    title: 'Shigeru Kawai SK-EX',
    slug: 'shigeru-kawai-sk-ex-ebony-polish',
    brandSlug: 'shigeru-kawai',
    model: 'SK-EX',
    finish: 'Ebony Polish',
    condition: 'display',
    location: 'Burlington',
    retailPrice: 234000,
    isAvailable: true,
    isFeatured: false,
    stockImageUrl: 'https://cdn.shopify.com/s/files/1/0740/4670/1723/files/Kawai-SK-EX.jpg?v=1768438069',
    specifications: { length: "9'1\"", width: '62"', keys: 88, pedals: 3 },
    tags: [{ tag: 'Concert Grand Piano' }, { tag: 'Japanese' }, { tag: 'Handcrafted' }],
  },
]

export async function seedPianos(payload: Payload): Promise<{ created: number; skipped: number }> {
  let created = 0
  let skipped = 0

  for (const piano of PIANO_INVENTORY) {
    // Pre-check: skip if slug already exists
    const existing = await payload.find({
      collection: 'pianos',
      where: { slug: { equals: piano.slug } },
      limit: 1,
    })

    if (existing.docs.length > 0) {
      payload.logger.info(`Piano "${piano.slug}" already exists — skipping.`)
      skipped++
      continue
    }

    const brandResult = await payload.find({
      collection: 'brands',
      where: { slug: { equals: piano.brandSlug } },
      limit: 1,
    })

    const brandId = brandResult.docs[0]?.id

    const { brandSlug: _b, ...pianoData } = piano

    try {
      await payload.create({
        collection: 'pianos',
        draft: true,
        data: {
          ...pianoData,
          ...(brandId ? { brand: brandId } : {}),
          _status: 'draft',
        },
      })

      payload.logger.info(`Created piano: ${piano.title}`)
      created++
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err)
      // Slug uniqueness conflict — another doc with this slug was created between
      // the pre-check and the create call, or slugField validation rejected it.
      if (message.toLowerCase().includes('slug')) {
        payload.logger.warn(`Skipping "${piano.slug}" — slug conflict: ${message}`)
        skipped++
      } else {
        // Unexpected error — re-throw so the caller knows something went wrong
        throw err
      }
    }
  }

  return { created, skipped }
}
