import React from 'react'
import type { Media } from '@/payload-types'
import { Media as MediaComponent } from '@/components/Media'

// Matches the ExpertBlock interface generated by Payload after type generation.
// Using a local type here so the component is valid before generate:types runs.
type ExpertBlockProps = {
  quote: string
  expertName: string
  expertRole?: string | null
  image?: string | Media | null
  style?: 'pullquote' | 'profile' | null
  id?: string | null
  blockName?: string | null
  blockType: 'expert'
  disableInnerContainer?: boolean
}

const C = {
  darkBg:     'hsl(350, 62%, 26%)',
  darkCard:   'hsl(350, 56%, 32%)',
  accent:     'hsl(40, 72%, 52%)',
  ivory:      'hsl(36, 22%, 96%)',
  mutedOnDark:'rgba(245, 235, 220, 0.52)',
  borderDark: 'hsl(350, 45%, 38%)',
}

function isMediaObject(val: string | Media | null | undefined): val is Media {
  return typeof val === 'object' && val !== null
}

// ── Pull Quote ──────────────────────────────────────────────────────────────
// Centred, large italic quote with gold rule and attribution beneath.
// Clean and editorial — works well mid-article.

function PullQuote({ quote, expertName, expertRole }: ExpertBlockProps) {
  return (
    <div
      className="relative my-16 mx-auto max-w-[52rem] px-8"
    >
      {/* Left gold bar */}
      <div
        className="absolute left-0 top-0 bottom-0 w-[3px]"
        style={{ backgroundColor: C.accent }}
      />

      <blockquote
        className="font-cormorant font-light italic leading-[1.45] mb-8"
        style={{
          fontSize: 'clamp(1.55rem, 2.4vw, 2.2rem)',
          color: C.darkBg,
        }}
      >
        &ldquo;{quote}&rdquo;
      </blockquote>

      <footer className="flex items-center gap-4">
        <div className="h-px w-6 shrink-0" style={{ backgroundColor: C.accent }} />
        <div>
          <p
            className="font-cormorant font-light leading-snug"
            style={{ fontSize: '1.1rem', color: C.darkBg }}
          >
            {expertName}
          </p>
          {expertRole && (
            <p
              className="font-display text-[9px] tracking-[0.38em] uppercase mt-1"
              style={{ color: 'hsl(350, 5%, 46%)' }}
            >
              {expertRole}
            </p>
          )}
        </div>
      </footer>
    </div>
  )
}

// ── Profile Card ────────────────────────────────────────────────────────────
// Dark burgundy card with photo, quote, name and role.
// More prominent — use for a featured expert callout.

function ProfileCard({ quote, expertName, expertRole, image }: ExpertBlockProps) {
  return (
    <div
      className="my-16 mx-auto max-w-[52rem]"
      style={{ backgroundColor: C.darkBg }}
    >
      {/* Gold top accent */}
      <div style={{ height: '3px', backgroundColor: C.accent }} />

      <div className="flex flex-col sm:flex-row gap-0">

        {/* Photo */}
        {isMediaObject(image) && (
          <div
            className="relative shrink-0 sm:w-[220px] aspect-[3/4] sm:aspect-auto overflow-hidden"
            style={{ backgroundColor: C.darkCard }}
          >
            <MediaComponent
              resource={image}
              fill
              imgClassName="object-cover object-top"
            />
          </div>
        )}

        {/* Content */}
        <div
          className="flex flex-col justify-between p-8 sm:p-10 flex-1"
        >
          <div>
            <div
              className="font-display text-[9px] tracking-[0.42em] uppercase mb-6"
              style={{ color: C.accent }}
            >
              Expert Insight
            </div>

            <blockquote
              className="font-cormorant font-light italic leading-[1.45] mb-8"
              style={{
                fontSize: 'clamp(1.4rem, 2.2vw, 2rem)',
                color: C.ivory,
              }}
            >
              &ldquo;{quote}&rdquo;
            </blockquote>
          </div>

          <footer
            className="pt-6 flex items-center gap-4"
            style={{ borderTop: `1px solid ${C.borderDark}` }}
          >
            <div
              className="w-9 h-9 flex items-center justify-center shrink-0"
              style={{ border: `1px solid ${C.borderDark}` }}
            >
              <span
                className="font-display text-[9px] tracking-wider"
                style={{ color: C.accent }}
              >
                {expertName.charAt(0)}
              </span>
            </div>
            <div>
              <p
                className="font-cormorant font-light"
                style={{ fontSize: '1.1rem', color: C.ivory, lineHeight: 1.2 }}
              >
                {expertName}
              </p>
              {expertRole && (
                <p
                  className="font-display text-[9px] tracking-[0.35em] uppercase mt-1"
                  style={{ color: C.mutedOnDark }}
                >
                  {expertRole}
                </p>
              )}
            </div>
          </footer>
        </div>
      </div>
    </div>
  )
}

// ── Main Export ─────────────────────────────────────────────────────────────

export const ExpertBlock: React.FC<ExpertBlockProps> = (props) => {
  const { style = 'pullquote' } = props

  if (style === 'profile') {
    return <ProfileCard {...props} />
  }

  return <PullQuote {...props} />
}
