/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    brands: Brand;
    pianos: Piano;
    testimonials: Testimonial;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    pianos: PianosSelect<false> | PianosSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | HeroHomepageBlock
    | TickerBlock
    | BrandRowsBlock
    | ShowroomGalleryBlock
    | PhilosophyBlock
    | FeaturedPianosBlock
    | NewsSectionBlock
    | LocationsBlock
    | FinalCtaBlock
    | SectionHeaderBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * Featured image shown at the top of the post (recommended: 1600×900px)
   */
  heroImage?: (string | null) | Media;
  /**
   * Build the post body by adding, reordering, and configuring blocks. Each block type has its own fields and renders independently.
   */
  layout?: (ExpertBlock | ContentBlock | MediaBlock | BannerBlock | CallToActionBlock)[] | null;
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  /**
   * Mark this post as a News item
   */
  isNews?: boolean | null;
  /**
   * Mark this post as a Guide
   */
  isGuide?: boolean | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Media library for images, videos, and documents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility and SEO. Describe what the image shows.
   */
  alt?: string | null;
  /**
   * Optional caption displayed with the image
   */
  caption?: string | null;
  /**
   * Detailed description for administrative purposes
   */
  description?: string | null;
  /**
   * Type of media for better organization
   */
  mediaType?: ('image' | 'video' | 'audio' | 'document') | null;
  /**
   * Video-specific metadata
   */
  videoMeta?: {
    /**
     * Video duration in seconds
     */
    duration?: number | null;
    /**
     * Custom thumbnail for the video
     */
    thumbnail?: (string | null) | Media;
    /**
     * Should this video autoplay (use sparingly)
     */
    autoplay?: boolean | null;
    /**
     * Start video muted (recommended for autoplay)
     */
    muted?: boolean | null;
  };
  /**
   * SEO and technical metadata
   */
  seoMeta?: {
    /**
     * Keywords this image relates to (comma-separated)
     */
    focusKeywords?: string | null;
    /**
     * Photo credit information
     */
    photographerCredit?: string | null;
    /**
     * Copyright or licensing information
     */
    copyrightInfo?: string | null;
    /**
     * Original source or URL if external
     */
    originalSource?: string | null;
  };
  /**
   * Mark as featured media for easy access
   */
  featured?: boolean | null;
  /**
   * Tags for organization and search
   */
  tags?: string[] | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExpertBlock".
 */
export interface ExpertBlock {
  /**
   * The expert quote or key insight to highlight
   */
  quote: string;
  expertName: string;
  /**
   * e.g. "Registered Piano Technician · 30 Years"
   */
  expertRole?: string | null;
  /**
   * Optional headshot or portrait
   */
  image?: (string | null) | Media;
  /**
   * Controls how the block renders on the page
   */
  style?: ('pullquote' | 'profile') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'expert';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Visual presentation of the call-to-action section.
   */
  style?: ('light' | 'dark' | 'ruled') | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomepageBlock".
 */
export interface HeroHomepageBlock {
  /**
   * Small text above the wordmark (e.g. 'Est. 1980 · Massachusetts')
   */
  eyebrow?: string | null;
  /**
   * Main heading displayed in large italic Cormorant Garamond (e.g. 'UsedSteinways')
   */
  heading?: string | null;
  /**
   * Small gold uppercase label below the heading (e.g. 'Quality Instruments · Expert Hands')
   */
  subLabel?: string | null;
  /**
   * Body paragraph shown below the sub-label
   */
  tagline?: string | null;
  /**
   * Monogram badge displayed above the heading (recommended: 110×110px)
   */
  logoImage?: (string | null) | Media;
  /**
   * Images that cycle in the right panel (min 2 recommended for crossfade)
   */
  heroImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Key numbers displayed below the CTAs
   */
  stats?:
    | {
        /**
         * e.g. '45+'
         */
        number?: string | null;
        /**
         * e.g. 'Years'
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  primaryCta?: {
    /**
     * e.g. 'Browse Collection'
     */
    label?: string | null;
    /**
     * e.g. '/pianos'
     */
    href?: string | null;
  };
  secondaryCta?: {
    /**
     * e.g. 'Get in Touch'
     */
    label?: string | null;
    /**
     * e.g. '/contact'
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroHomepage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TickerBlock".
 */
export interface TickerBlock {
  /**
   * Brand names or labels that scroll across the ticker bar. Leave empty to use the default brand list.
   */
  items?:
    | {
        /**
         * e.g. 'Steinway & Sons'
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Background color of the ticker bar
   */
  style?: ('dark' | 'light') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ticker';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandRowsBlock".
 */
export interface BrandRowsBlock {
  /**
   * Full-width brand category links with large editorial typography. Leave empty to auto-render the three default rows (Steinway & Sons, Handcrafted European, Shigeru Kawai) pulled live from the Brands collection. Add rows to control order, mix in custom rows, or override the auto-derived copy.
   */
  rows?:
    | {
        /**
         * Auto-derive this row from a Brands-collection category, or build it manually with "Custom".
         */
        source?: ('steinway' | 'european' | 'shigeru-kawai' | 'custom') | null;
        /**
         * Overrides the auto-derived heading. Required for Custom rows.
         */
        heading?: string | null;
        /**
         * Overrides the auto eyebrow (e.g. 'United States · Est. 1853').
         */
        eyebrow?: string | null;
        /**
         * Overrides the brand tagline shown below the heading.
         */
        tagline?: string | null;
        /**
         * Overrides the auto link (e.g. '/steinway'). Required for Custom rows.
         */
        href?: string | null;
        /**
         * Defaults to 'Browse Collection' if left empty.
         */
        ctaLabel?: string | null;
        /**
         * Overrides the auto-derived model/brand pill badges when one or more are set.
         */
        tags?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Overrides the default background (Steinway & Shigeru = light, European = dark).
         */
        style?: ('light' | 'dark') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandRows';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowroomGalleryBlock".
 */
export interface ShowroomGalleryBlock {
  /**
   * Overline label above the heading
   */
  eyebrow?: string | null;
  /**
   * Section heading — use \n for line breaks
   */
  heading?: string | null;
  /**
   * Gallery images for the bento grid (min 6 recommended)
   */
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * URL for the "View Full Gallery" button
   */
  galleryHref?: string | null;
  /**
   * URL for the "Visit Our Showroom" button
   */
  showroomHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'showroomGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhilosophyBlock".
 */
export interface PhilosophyBlock {
  /**
   * Small label above the heading (e.g. 'Our Philosophy')
   */
  eyebrow?: string | null;
  /**
   * Large display heading — use \n for line breaks
   */
  heading?: string | null;
  /**
   * Body paragraph beneath the heading — use \n for line breaks
   */
  body?: string | null;
  /**
   * Full-bleed image shown with a dark overlay behind the text
   */
  backgroundImage?: (string | null) | Media;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'philosophy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPianosBlock".
 */
export interface FeaturedPianosBlock {
  /**
   * Internal label for this block (e.g. 'Featured Instruments')
   */
  heading?: string | null;
  /**
   * Caps how many pinned pianos are shown. Only applies when specific pianos are pinned below — the automatic fallback always matches the static homepage carousel.
   */
  limit?: number | null;
  /**
   * Leave empty to render the exact same featured-pianos carousel as the static homepage. Add rows to pin specific instruments and override the default selection.
   */
  pianos?:
    | {
        piano?: (string | null) | Piano;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredPianos';
}
/**
 * Individual piano listings available for sale.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pianos".
 */
export interface Piano {
  id: string;
  /**
   * e.g. "2015 Steinway Model B — Satin Ebony"
   */
  title: string;
  brand?: (string | null) | Brand;
  /**
   * e.g. "Model B"
   */
  model?: string | null;
  /**
   * Year the piano was originally built
   */
  year?: number | null;
  /**
   * Year the piano was rebuilt/restored, if applicable
   */
  rebuiltYear?: number | null;
  serialNumber?: string | null;
  /**
   * e.g. "Satin Ebony"
   */
  finish?: string | null;
  specifications?: {
    /**
     * e.g. "6'10""
     */
    length?: string | null;
    /**
     * e.g. "58"
     */
    width?: string | null;
    stringLength?: string | null;
    keys?: number | null;
    pedals?: number | null;
  };
  /**
   * e.g. 89500. Only shown publicly when "Show Price" is checked.
   */
  price?: number | null;
  /**
   * Optional. Original price when new — shows value contrast to buyers.
   */
  retailPrice?: number | null;
  condition: 'new' | 'used' | 'reconditioned' | 'rebuilt' | 'rebuilt-partial' | 'work-in-progress' | 'display';
  /**
   * Detailed notes on the piano's current condition.
   */
  conditionReport?: string | null;
  /**
   * Main listing description shown on the piano detail page. Paste from any source — formatting (bold, italic) is preserved and line-wrap breaks are automatically cleaned up. Provenance and restoration notes have their own fields below.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional freeform tags e.g. "concert-quality", "single-owner"
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload piano photos. First image is used as the listing thumbnail.
   */
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional reference image from the brand website. Used as a fallback when no photos have been uploaded yet.
   */
  stockImageUrl?: string | null;
  /**
   * Optional YouTube or Vimeo link.
   */
  videoUrl?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Which showroom this piano is physically located at.
   */
  location?: ('Natick' | 'Burlington' | 'Incoming') | null;
  /**
   * Uncheck when the piano has been sold.
   */
  isAvailable?: boolean | null;
  /**
   * Featured pianos appear prominently on the homepage.
   */
  isFeatured?: boolean | null;
  /**
   * Controls grid order. Lower number = appears first. Default is 20 — use 1–19 to promote, 21+ to demote.
   */
  priority?: number | null;
  /**
   * When off (default), the public listing shows "Call for Pricing" instead of the price.
   */
  showPrice?: boolean | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Piano brands with embedded model specifications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  /**
   * e.g. "Steinway & Sons"
   */
  name: string;
  /**
   * e.g. "steinway"
   */
  slug: string;
  country?: string | null;
  founded?: number | null;
  category?: ('steinway' | 'european' | 'shigeru-kawai' | 'other') | null;
  prestige?: ('Ultra Premium' | 'Premium' | 'Professional') | null;
  tagline?: string | null;
  description?: string | null;
  whyBuyPreowned?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "$30,000 – $200,000+"
   */
  priceRange?: string | null;
  accentColor?: string | null;
  /**
   * When set, shown as a static hero at the top of the brand page (over the brand name / tagline). Leave empty to use the automatic piano carousel.
   */
  heroImage?: (string | null) | Media;
  /**
   * Piano models offered by this brand.
   */
  models?:
    | {
        /**
         * e.g. "Model B"
         */
        name: string;
        /**
         * e.g. "model-b"
         */
        slug: string;
        type: 'Grand' | 'Upright' | 'Concert Grand';
        /**
         * e.g. "6'10""
         */
        size?: string | null;
        /**
         * e.g. "82"
         */
        sizeInches?: string | null;
        weight?: string | null;
        stringLength?: string | null;
        /**
         * e.g. "1884 – present"
         */
        yearRange?: string | null;
        description: string;
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        priceGuide?:
          | {
              era: string;
              condition: string;
              priceRange: string;
              id?: string | null;
            }[]
          | null;
        adjacentModels?:
          | {
              adjacentSlug: string;
              adjacentName: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Lower numbers appear first
         */
        order?: number | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsSectionBlock".
 */
export interface NewsSectionBlock {
  /**
   * Internal label (e.g. 'Latest News')
   */
  heading?: string | null;
  /**
   * How many recent published posts to display
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationsBlock".
 */
export interface LocationsBlock {
  /**
   * Small uppercase label above the tabs (e.g. 'Our Locations').
   */
  eyebrow?: string | null;
  /**
   * Optional large heading rendered above the location tabs. Leave blank to omit.
   */
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FinalCtaBlock".
 */
export interface FinalCtaBlock {
  /**
   * Small label above the heading (e.g. 'Burlington & Natick Showrooms')
   */
  eyebrow?: string | null;
  /**
   * Large display heading — use \n for line breaks
   */
  heading?: string | null;
  /**
   * Body paragraph beneath the heading
   */
  body?: string | null;
  /**
   * Filled primary call-to-action button
   */
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Outline secondary call-to-action button
   */
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Where to pull the inline phone number from
   */
  phoneSource?: ('siteSettings' | 'custom') | null;
  /**
   * Custom phone number to display (used only when Phone Number Source is set to Custom Override)
   */
  phoneOverride?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'finalCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeaderBlock".
 */
export interface SectionHeaderBlock {
  /**
   * Small uppercase label above the heading (e.g. 'The Collection')
   */
  eyebrow?: string | null;
  /**
   * Giant italic display heading (e.g. 'Our Pianos')
   */
  heading?: string | null;
  /**
   * Optional supporting paragraph aligned bottom-right beside the heading
   */
  tagline?: string | null;
  /**
   * Section background color
   */
  style?: ('dark' | 'light') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Article headline for this testimonial
   */
  title: string;
  /**
   * Featured image displayed at the top of the testimonial page
   */
  featuredImage?: (string | null) | Media;
  /**
   * Full name of the customer
   */
  customerName: string;
  /**
   * City, State (e.g. "Waltham, MA")
   */
  location?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Show this testimonial in the featured carousel at the top of the testimonials page.
   */
  featured?: boolean | null;
  /**
   * Controls grid order. Lower number = appears first. Default is 20 — use 1–19 to promote, 21+ to demote.
   */
  priority?: number | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: string | Post;
      }
    | {
        relationTo: 'pianos';
        value: string | Piano;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'pianos';
        value: string | Piano;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        heroHomepage?: T | HeroHomepageBlockSelect<T>;
        ticker?: T | TickerBlockSelect<T>;
        brandRows?: T | BrandRowsBlockSelect<T>;
        showroomGallery?: T | ShowroomGalleryBlockSelect<T>;
        philosophy?: T | PhilosophyBlockSelect<T>;
        featuredPianos?: T | FeaturedPianosBlockSelect<T>;
        newsSection?: T | NewsSectionBlockSelect<T>;
        locations?: T | LocationsBlockSelect<T>;
        finalCta?: T | FinalCtaBlockSelect<T>;
        sectionHeader?: T | SectionHeaderBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  style?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomepageBlock_select".
 */
export interface HeroHomepageBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subLabel?: T;
  tagline?: T;
  logoImage?: T;
  heroImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TickerBlock_select".
 */
export interface TickerBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandRowsBlock_select".
 */
export interface BrandRowsBlockSelect<T extends boolean = true> {
  rows?:
    | T
    | {
        source?: T;
        heading?: T;
        eyebrow?: T;
        tagline?: T;
        href?: T;
        ctaLabel?: T;
        tags?:
          | T
          | {
              name?: T;
              id?: T;
            };
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowroomGalleryBlock_select".
 */
export interface ShowroomGalleryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  galleryHref?: T;
  showroomHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhilosophyBlock_select".
 */
export interface PhilosophyBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  backgroundImage?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPianosBlock_select".
 */
export interface FeaturedPianosBlockSelect<T extends boolean = true> {
  heading?: T;
  limit?: T;
  pianos?:
    | T
    | {
        piano?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsSectionBlock_select".
 */
export interface NewsSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationsBlock_select".
 */
export interface LocationsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FinalCtaBlock_select".
 */
export interface FinalCtaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  phoneSource?: T;
  phoneOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeaderBlock_select".
 */
export interface SectionHeaderBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  tagline?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        expert?: T | ExpertBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
      };
  relatedPosts?: T;
  categories?: T;
  isNews?: T;
  isGuide?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExpertBlock_select".
 */
export interface ExpertBlockSelect<T extends boolean = true> {
  quote?: T;
  expertName?: T;
  expertRole?: T;
  image?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  description?: T;
  mediaType?: T;
  videoMeta?:
    | T
    | {
        duration?: T;
        thumbnail?: T;
        autoplay?: T;
        muted?: T;
      };
  seoMeta?:
    | T
    | {
        focusKeywords?: T;
        photographerCredit?: T;
        copyrightInfo?: T;
        originalSource?: T;
      };
  featured?: T;
  tags?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  founded?: T;
  category?: T;
  prestige?: T;
  tagline?: T;
  description?: T;
  whyBuyPreowned?:
    | T
    | {
        text?: T;
        id?: T;
      };
  priceRange?: T;
  accentColor?: T;
  heroImage?: T;
  models?:
    | T
    | {
        name?: T;
        slug?: T;
        type?: T;
        size?: T;
        sizeInches?: T;
        weight?: T;
        stringLength?: T;
        yearRange?: T;
        description?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        priceGuide?:
          | T
          | {
              era?: T;
              condition?: T;
              priceRange?: T;
              id?: T;
            };
        adjacentModels?:
          | T
          | {
              adjacentSlug?: T;
              adjacentName?: T;
              id?: T;
            };
        order?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pianos_select".
 */
export interface PianosSelect<T extends boolean = true> {
  title?: T;
  brand?: T;
  model?: T;
  year?: T;
  rebuiltYear?: T;
  serialNumber?: T;
  finish?: T;
  specifications?:
    | T
    | {
        length?: T;
        width?: T;
        stringLength?: T;
        keys?: T;
        pedals?: T;
      };
  price?: T;
  retailPrice?: T;
  condition?: T;
  conditionReport?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  stockImageUrl?: T;
  videoUrl?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  location?: T;
  isAvailable?: T;
  isFeatured?: T;
  priority?: T;
  showPrice?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  customerName?: T;
  location?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  priority?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
    /**
     * Displayed in the footer and on the contact/visit pages.
     */
    hoursOfOperation?: string | null;
  };
  /**
   * Add one entry per physical location.
   */
  locations?:
    | {
        /**
         * e.g. "Natick" or "Burlington"
         */
        name: string;
        streetAddress: string;
        city: string;
        state: string;
        zip: string;
        /**
         * Full Google Maps link for the "Get Directions" button.
         */
        googleMapsUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform:
          | 'facebook'
          | 'instagram'
          | 'twitter'
          | 'linkedin'
          | 'youtube'
          | 'tiktok'
          | 'github'
          | 'discord'
          | 'threads'
          | 'other';
        url: string;
        /**
         * Overrides the platform name when displayed as link text
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        hoursOfOperation?: T;
      };
  locations?:
    | T
    | {
        name?: T;
        streetAddress?: T;
        city?: T;
        state?: T;
        zip?: T;
        googleMapsUrl?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'pianos';
          value: string | Piano;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: string | Testimonial;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}